---
title: "Sequential One-Way ANOVA"
author: "Meike Steinhilber"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 4
description: >
  This vignette describes the sequential one-way ANOVA.
vignette: >
  %\VignetteIndexEntry{Sequential One-Way ANOVA}
  %\VignetteEncoding{UTF-8}{inputenc}
  %\VignetteEngine{knitr::rmarkdown}
bibliography: references.bib
csl: "apa.csl"
---

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE
)
```

# ```{r, child="children/sprts.Rmd"}
# 
# ```


## What is the sequential one-way ANOVA?

The sequential one-way fixed effects ANOVA is based on the Sequential Probability Ratio Test (SPRT) by Abraham @wald1947, which is a highly efficient sequential hypothesis test.
However, the usage of WaldÂ´s SPRT is limited in the case of normally distributed data, because the variance has to be known or specified in the hypothesis.
Other variants like the sequential *t*-test or the sequential one-way ANOVA have been developed to increase the applicability of SPRTs, see [@schnuerch2020; @steinhilber2023a].


The basic idea is to transform the sequence of observations (which is dependent on the variance) into a sequence of the associated *t*-statistic (which is *in*dependent of the variance).

In the SPRT the null and alternative hypotheses are defined as follows, with ğœƒ representing the model parameter :

$$
H_0:\ ğœƒ\ =\ ğœƒ_0 \\
H_1:\ ğœƒ\ =\ ğœƒ_1
$$

The test statistic of the SPRT is based on a likelihood ratio, which is a measure of the relative evidence in the data for the given hypotheses. More specifically, it is the ratio of the likelihood of the alternative hypothesis to the likelihood of the null hypothesis at the *m*-th step of the sampling process (LR~m~).

$$
LR_{m} 
= \frac {f(data_m | H_1)} {f(data_m | H_0)}
= \frac {ğ‘“(x_1,...,x_m | ğœƒ_1)} {ğ‘“(x_1,...,x_m  | ğœƒ_0)} 
$$

Before the transformation into the *t*-statistic, the model parameter ğœƒ contains the parameters of a normal distribution: the mean (*Âµ*) and the standard deviation (ğœ). Therefore, the Wald SPRT requires prior knowledge about the variance (ğœ^2^) or a specification in the hypotheses.

After the transformation of the observed values into the associated t-statistic, the model parameter ğœƒ contains the parameters of the non-central t-distribution: the degrees of freedom (*df*) and the non-centrality parameter (ğ›¥).

$$
{ğ‘“(x_1,...,x_m | Âµ,ğœ)} => {ğ‘“(t_2,...,t_m  | df,ğ›¥)} 
$$

For the calculation of the degrees of freedom, only the sample size of the group(s) is needed. The non-centrality parameter also requires a specification of the expected effect size in form of Cohen\`s d (*d*).

To eventually calculate the LR of the sequential *t*-test, only the current t~*m*~-statistic is necessary. @rushton1950a demonstrated that an SPRT can be performed by simply considering the ratio of probability densities for the most recent t~*m*~ statistic under the alternative and null hypothesis at any *m-*th stage. Thus, the test statistic for a one and two-sided sequential t-test can be calculated as follows:

$$
LR_{m,\ one-sided\ sequential\ t-test} 
= \frac {ğ‘“(t_m | ğœƒ_1)} {ğ‘“(t_m | ğœƒ_0)}
\\
LR_{m,\ two-sided\ sequential\ t-test} 
= \frac {ğ‘“(t_m^2 | ğœƒ_1)} {ğ‘“(t_m^2 | ğœƒ_0)}.
$$

To account for the fact that the algebraic sign is unknown in a two-sided test, the *t*-value is squared [@rushton1952].

After the calculation of the test statistic, the decision will be either to continue sampling or to terminate the sampling and accept one of the hypotheses. @wald1945a defined the following rules for the SPRT:

|    Condition    |                    Decision |
|:---------------:|----------------------------:|
|    LR~m~ â‰¤ B    | accept H~0~ and reject H~1~ |
| B \< LR~m~ \< A |           continue sampling |
|    LR~m~ â‰¤ A    | accept H~1~ and reject H~0~ |

The A and B boundaries are calculated with the previously defined error rates ğ›¼ (Type I error) and ğ›½ (Type II error) as follows:

$$
A = \left( \frac{1 - ğ›½}{ğ›¼} \right) \\
B = \left( \frac{ğ›½}{1 - ğ›¼} \right).
$$

In summary, three specifications are required to calculate a sequential *t*-test:

-   the ğ›¼ error probability (usually 0.05 or less),

-   the ğ›½ error probability (usually .20 or less), and

-   CohenÂ´s d (either as the expected effect size or as the lower limit for a substantial effect).

## What is the sequential one-way ANOVA?

The sequential one-way fixed effects ANOVA is also a variant of SPRTs but can be used if the means of two or more groups are compared.
The b


## References
