<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Use Case • sprtt</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="96x96" href="../favicon-96x96.png">
<link rel="icon" type="”image/svg+xml”" href="../favicon.svg">
<link rel="apple-touch-icon" sizes="180x180" href="../apple-touch-icon.png">
<link rel="icon" sizes="any" href="../favicon.ico">
<link rel="manifest" href="../site.webmanifest">
<script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../deps/bootstrap-5.3.1/bootstrap.min.css" rel="stylesheet">
<script src="../deps/bootstrap-5.3.1/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet">
<link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet">
<script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Use Case">
</head>
<body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-light" data-bs-theme="light" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">sprtt</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">0.2.0</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto">
<li class="nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="active nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-articles" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Articles</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-articles">
<li><hr class="dropdown-divider"></li>
    <li><h6 class="dropdown-header" data-toc-skip>Getting Started</h6></li>
    <li><a class="dropdown-item" href="../articles/usage_sprtt.html">How to use the sprtt package</a></li>
    <li><a class="dropdown-item" href="../articles/use_case.html">Use Case</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><h6 class="dropdown-header" data-toc-skip>Sequential Tests</h6></li>
    <li><a class="dropdown-item" href="../articles/t_test.html">Sequential t-Test</a></li>
    <li><a class="dropdown-item" href="../articles/one_way_anova.html">Sequential One-Way ANOVA</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><h6 class="dropdown-header" data-toc-skip>Further Topics</h6></li>
    <li><a class="dropdown-item" href="../articles/sprts.html">SPRTs</a></li>
  </ul>
</li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Changelog</a></li>
      </ul>
<ul class="navbar-nav">
<li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json">
</form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/MeikeSteinhilber/sprtt/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul>
</div>


  </div>
</nav><div class="container template-article">




<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">
      <img src="../logo.png" class="logo" alt=""><h1>Use Case</h1>
                        <h4 data-toc-skip class="author">Meike
Steinhilber</h4>
            
            <h4 data-toc-skip class="date">2025-10-06</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/MeikeSteinhilber/sprtt/blob/develop/vignettes/use_case.Rmd" class="external-link"><code>vignettes/use_case.Rmd</code></a></small>
      <div class="d-none name"><code>use_case.Rmd</code></div>
    </div>

    
    
<div class="section level2">
<h2 id="note">Note<a class="anchor" aria-label="anchor" href="#note"></a>
</h2>
<ul>
<li><p>The data set <code>df_stress</code> is included in the
<code>sprtt</code> package. Thus, the data set is available when the
package is loaded.</p></li>
<li>
<p>In the R code sections:</p>
<ul>
<li>
<code># comment</code>: is a comment</li>
<li>
<code>function()</code>: is R code</li>
<li>
<code>#&gt; results of function()</code>: is console output</li>
</ul>
</li>
</ul>
</div>
<div class="section level2">
<h2 id="overview">Overview<a class="anchor" aria-label="anchor" href="#overview"></a>
</h2>
<p>The <code>sprtt</code> package is a <strong>s</strong>equential
<strong>p</strong>robability <strong>r</strong>atio
<strong>t</strong>ests toolbox (<strong>sprtt</strong>). This vignette
describes an exemplary use case to improve the understanding of the
package and the sequential t-test.</p>
<p>Other recommended vignettes cover:</p>
<ul>
<li><p><a href="https://meikesteinhilber.github.io/sprtt/articles/sequential_testing.html">the
theoretical background</a> and</p></li>
<li><p>a <a href="https://meikesteinhilber.github.io/sprtt/articles/usage-sprtt.html">general
guide</a>, how to use the package.</p></li>
</ul>
</div>
<div class="section level2">
<h2 id="use-case">Use Case<a class="anchor" aria-label="anchor" href="#use-case"></a>
</h2>
<p>A team of researchers wants to know if the stress of the employees
increased in the company itFlow AG over the last year. The Human
Resources department has gathered data from a new self-care tool they
implemented for the employees. It is difficult to predict how many
employees will participate at the second measurement point (one year
after the baseline). The team suggests using a sequential
<em>t</em>-test instead of a Students <em>t</em>-test, because the
sequential procedure can reduce the required sample size and is stopped
right after the decision for one of the hypotheses is made. Furthermore,
the sequential <em>t</em>-test is able to gather evidence for both the
alternative and the null hypothesis.</p>
<div class="section level3">
<h3 id="hypothesis">Hypothesis<a class="anchor" aria-label="anchor" href="#hypothesis"></a>
</h3>
<p>The researchers know that the company has received more orders than
in the year before. Thus, they expect an increase in self-reported
stress.</p>
</div>
<div class="section level3">
<h3 id="data-analysis">Data Analysis<a class="anchor" aria-label="anchor" href="#data-analysis"></a>
</h3>
<p>The parameters of the sequential <em>t</em>-test are specified as
follows:</p>
<ul>
<li>
<p>The researchers expect an increase in stress but they have no
prior knowledge about the expected effect size. Thus, they define the
lower limit of a substantial effect of interest.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">d</span> <span class="op">&lt;-</span> <span class="fl">0.2</span></span></code></pre></div>
</li>
<li>
<p>They choose the common
<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>α</mi><annotation encoding="application/x-tex">\alpha</annotation></semantics></math>
level of .05 and the same level for the
<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>β</mi><annotation encoding="application/x-tex">\beta</annotation></semantics></math>
error probability, which leads to a power of .95
(<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mn>1</mn><mo>−</mo><mi>β</mi></mrow><annotation encoding="application/x-tex">1 - \beta</annotation></semantics></math>).</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">alpha</span> <span class="op">&lt;-</span> <span class="fl">0.05</span></span>
<span><span class="va">power</span> <span class="op">&lt;-</span> <span class="fl">0.95</span></span></code></pre></div>
</li>
<li>
<p>The data are repeated measures, therefore the test is a paired
sequential <em>t</em>-test.</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">paired</span> <span class="op">&lt;-</span> <span class="cn">TRUE</span></span></code></pre></div>
</li>
<li>
<p>The researchers expect that the stress will have increased after
one year. Thus, they specify that the true difference in means is
greater than 0.<br><code>(mean(one_year_stress) - mean(baseline_stress)) &gt; 0</code></p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">alternative</span> <span class="op">&lt;-</span> <span class="st">"greater"</span></span></code></pre></div>
</li>
</ul>
<p>The HR department receives the new data piece by piece and passes it
directly on to the researchers. The test is performed for the first time
and starts with the first two data points.</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># first data from the Human Resources department ---</span></span>
<span><span class="co"># current sample size</span></span>
<span><span class="va">n_person</span> <span class="op">&lt;-</span> <span class="fl">2</span></span>
<span></span>
<span><span class="co"># get data</span></span>
<span><span class="va">df</span> <span class="op">&lt;-</span> <span class="va">df_stress</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="va">n_person</span>,<span class="op">]</span></span>
<span></span>
<span><span class="co"># print data</span></span>
<span><span class="va">df</span></span>
<span><span class="co">#&gt;   baseline_stress one_year_stress</span></span>
<span><span class="co">#&gt; 1        7.175250        7.844337</span></span>
<span><span class="co">#&gt; 2        4.918343        5.527191</span></span>
<span></span>
<span><span class="co"># sequential t-test</span></span>
<span><span class="va">results</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/seq_ttest.html">seq_ttest</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">one_year_stress</span>,</span>
<span>                     <span class="va">df</span><span class="op">$</span><span class="va">baseline_stress</span>,</span>
<span>                     alpha <span class="op">=</span> <span class="va">alpha</span>,</span>
<span>                     power <span class="op">=</span> <span class="va">power</span>,</span>
<span>                     d <span class="op">=</span> <span class="va">d</span>,</span>
<span>                     paired <span class="op">=</span> <span class="va">paired</span>,</span>
<span>                     alternative <span class="op">=</span> <span class="va">alternative</span>,</span>
<span>                     verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># print results: console output</span></span>
<span><span class="va">results</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; *****  Sequential Paired t-test *****</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; formula: df$one_year_stress and  df$baseline_stress</span></span>
<span><span class="co">#&gt; test statistic:</span></span>
<span><span class="co">#&gt;  log-likelihood ratio = 0.332, decision = continue sampling</span></span>
<span><span class="co">#&gt; SPRT thresholds:</span></span>
<span><span class="co">#&gt;  lower log(B) = -2.944, upper log(A) = 2.944</span></span></code></pre></div>
<p>The decision from the first test is:</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">results</span><span class="op">@</span><span class="va">decision</span></span>
<span><span class="co">#&gt; [1] "continue sampling"</span></span></code></pre></div>
<p>As a result, the researchers take one more data point and run the
test again.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># new data from the Human Resources department ---</span></span>
<span><span class="co"># get one more person</span></span>
<span><span class="va">n_person</span> <span class="op">&lt;-</span> <span class="va">n_person</span> <span class="op">+</span> <span class="fl">1</span></span>
<span><span class="va">df</span> <span class="op">&lt;-</span> <span class="va">df_stress</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="va">n_person</span>,<span class="op">]</span></span>
<span></span>
<span><span class="co"># print new data</span></span>
<span><span class="va">df</span></span>
<span><span class="co">#&gt;   baseline_stress one_year_stress</span></span>
<span><span class="co">#&gt; 1        7.175250        7.844337</span></span>
<span><span class="co">#&gt; 2        4.918343        5.527191</span></span>
<span><span class="co">#&gt; 3        4.634266        5.783046</span></span>
<span></span>
<span><span class="co"># sequential t-test</span></span>
<span><span class="va">results</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/seq_ttest.html">seq_ttest</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">one_year_stress</span>,</span>
<span>                     <span class="va">df</span><span class="op">$</span><span class="va">baseline_stress</span>,</span>
<span>                     alpha <span class="op">=</span> <span class="va">alpha</span>,</span>
<span>                     power <span class="op">=</span> <span class="va">power</span>,</span>
<span>                     d <span class="op">=</span> <span class="va">d</span>,</span>
<span>                     paired <span class="op">=</span> <span class="va">paired</span>,</span>
<span>                     alternative <span class="op">=</span> <span class="va">alternative</span>,</span>
<span>                     verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># print results</span></span>
<span><span class="va">results</span><span class="op">@</span><span class="va">decision</span></span>
<span><span class="co">#&gt; [1] "continue sampling"</span></span></code></pre></div>
<p>This process is repeated until the decision is made for one of the
two hypotheses. To simulate this sequential process, a while-loop
embraces the sequential <em>t</em>-test function in the code below,
which will not stop until one of the hypotheses is accepted or the
maximum of the data is reached.</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># define the starting point</span></span>
<span><span class="va">decision</span> <span class="op">&lt;-</span> <span class="st">"continue sampling"</span></span>
<span><span class="va">n_person</span> <span class="op">&lt;-</span> <span class="fl">3</span></span>
<span></span>
<span><span class="co"># simulation of the sequential procedure</span></span>
<span><span class="kw">while</span><span class="op">(</span><span class="va">decision</span> <span class="op">==</span> <span class="st">"continue sampling"</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="co"># get the current data</span></span>
<span>  <span class="va">df</span> <span class="op">&lt;-</span> <span class="va">df_stress</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="va">n_person</span>,<span class="op">]</span></span>
<span>  </span>
<span>  <span class="co"># run the sequential test and save the results</span></span>
<span>  <span class="va">results</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/seq_ttest.html">seq_ttest</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">one_year_stress</span>,</span>
<span>                       <span class="va">df</span><span class="op">$</span><span class="va">baseline_stress</span>,</span>
<span>                       alpha <span class="op">=</span> <span class="va">alpha</span>,</span>
<span>                       power <span class="op">=</span> <span class="va">power</span>,</span>
<span>                       d <span class="op">=</span> <span class="va">d</span>,</span>
<span>                       paired <span class="op">=</span> <span class="va">paired</span>,</span>
<span>                       alternative <span class="op">=</span> <span class="va">alternative</span><span class="op">)</span></span>
<span>  <span class="co"># save the current desicion</span></span>
<span>  <span class="va">decision</span> <span class="op">&lt;-</span> <span class="va">results</span><span class="op">@</span><span class="va">decision</span></span>
<span>  </span>
<span>  <span class="co"># add a new person</span></span>
<span>  <span class="va">n_person</span> <span class="op">&lt;-</span> <span class="va">n_person</span> <span class="op">+</span> <span class="fl">1</span></span>
<span>  </span>
<span>  <span class="co"># break if the maximum of the data is reached</span></span>
<span>  <span class="kw">if</span> <span class="op">(</span><span class="va">n_person</span> <span class="op">&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html" class="external-link">nrow</a></span><span class="op">(</span><span class="va">df_stress</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="kw">break</span></span>
<span>  <span class="op">}</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="co"># console output</span></span>
<span><span class="va">results</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; *****  Sequential Paired t-test *****</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; formula: df$one_year_stress and  df$baseline_stress</span></span>
<span><span class="co">#&gt; test statistic:</span></span>
<span><span class="co">#&gt;  log-likelihood ratio = 2.988, decision = accept H1</span></span>
<span><span class="co">#&gt; SPRT thresholds:</span></span>
<span><span class="co">#&gt;  lower log(B) = -2.944, upper log(A) = 2.944</span></span>
<span><span class="co">#&gt; Log-Likelihood of the:</span></span>
<span><span class="co">#&gt;  alternative hypothesis = -2.238</span></span>
<span><span class="co">#&gt;  null hypothesis = -5.226</span></span>
<span><span class="co">#&gt; alternative hypothesis: true difference in means is greater than 0.</span></span>
<span><span class="co">#&gt; specified effect size: Cohen's d = 0.2</span></span>
<span><span class="co">#&gt; degrees of freedom: df = 47</span></span>
<span><span class="co">#&gt; sample estimates:</span></span>
<span><span class="co">#&gt; mean difference </span></span>
<span><span class="co">#&gt;         0.47931 </span></span>
<span><span class="co">#&gt; *Note: to get access to the object of the results use the @ or [] instead of the $ operator.</span></span></code></pre></div>
<p>The while-loop comes to an end after 48 data points.</p>
</div>
<div class="section level3">
<h3 id="report-results">Report Results<a class="anchor" aria-label="anchor" href="#report-results"></a>
</h3>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Required results for the report</span></span>
<span></span>
<span><span class="co"># likelihood ratio (LR)</span></span>
<span><span class="va">LR</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html" class="external-link">round</a></span><span class="op">(</span><span class="va">results</span><span class="op">@</span><span class="va">likelihood_ratio</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">LR</span></span>
<span><span class="co">#&gt; [1] 19.85</span></span>
<span></span>
<span><span class="co"># sample size (N) = degrees of freedom +2 (two-samples) or +1 (one-sample &amp; paired)</span></span>
<span><span class="va">N</span> <span class="op">&lt;-</span> <span class="va">results</span><span class="op">@</span><span class="va">df</span> <span class="op">+</span> <span class="fl">1</span></span>
<span><span class="va">N</span></span>
<span><span class="co">#&gt; [1] 48</span></span>
<span></span>
<span><span class="co"># baseline stress (M and SD)</span></span>
<span><span class="va">mean_t1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html" class="external-link">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html" class="external-link">mean</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">baseline_stress</span><span class="op">)</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">mean_t1</span></span>
<span><span class="co">#&gt; [1] 4.99</span></span>
<span><span class="va">sd_t1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html" class="external-link">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html" class="external-link">sd</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">baseline_stress</span><span class="op">)</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">sd_t1</span></span>
<span><span class="co">#&gt; [1] 1.02</span></span>
<span></span>
<span><span class="co"># after one year stress (M and SD)</span></span>
<span><span class="va">mean_t2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html" class="external-link">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html" class="external-link">mean</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">one_year_stress</span><span class="op">)</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">mean_t2</span></span>
<span><span class="co">#&gt; [1] 5.47</span></span>
<span><span class="va">sd_t2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html" class="external-link">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html" class="external-link">sd</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">one_year_stress</span><span class="op">)</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">sd_t2</span></span>
<span><span class="co">#&gt; [1] 1.53</span></span>
<span></span>
<span><span class="co"># NOT INCLUDED IN THE PACKAGE </span></span>
<span></span>
<span><span class="co"># calculate effect size: Cohen´s d</span></span>
<span><span class="va">d_results</span> <span class="op">&lt;-</span> <span class="fu">effsize</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/effsize/man/cohen.d.html" class="external-link">cohen.d</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">one_year_stress</span>,</span>
<span>                 <span class="va">df</span><span class="op">$</span><span class="va">baseline_stress</span>,</span>
<span>                 paired <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">d</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html" class="external-link">round</a></span><span class="op">(</span><span class="va">d_results</span><span class="op">$</span><span class="va">estimate</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">d</span></span>
<span><span class="co">#&gt; [1] 0.34</span></span>
<span></span>
<span><span class="co"># confidence intervall</span></span>
<span><span class="va">d_lower</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html" class="external-link">round</a></span><span class="op">(</span><span class="va">d_results</span><span class="op">$</span><span class="va">conf.int</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">d_lower</span></span>
<span><span class="co">#&gt; [1] 0.11</span></span>
<span><span class="va">d_upper</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html" class="external-link">round</a></span><span class="op">(</span><span class="va">d_results</span><span class="op">$</span><span class="va">conf.int</span><span class="op">[[</span><span class="fl">2</span><span class="op">]</span><span class="op">]</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">d_upper</span></span>
<span><span class="co">#&gt; [1] 0.57</span></span></code></pre></div>
<p>Starting at <em>N</em> = 2, the test stops sampling at a total sample
size of <em>N</em> = 48 with <em>LR</em><sub>48</sub> = 19.85. This
ratio indicates that the data are about 20 times more likely under
H<sub>1</sub> than under H<sub>0</sub>. Thus, we accept the alternative
hypothesis: The perceived stress at the second measurement (<em>M</em> =
5.47, <em>SD</em> = 1.53) is higher than one year ago at the baseline
measurement (<em>M</em> = 4.99, <em>SD</em> = 1.02), Cohen`s <em>d</em>
= 0.34, 95% CI [0.11, 0.57].<a class="footnote-ref" tabindex="0" data-bs-toggle="popover" data-bs-content='&lt;p&gt;The citation style was taken from &lt;span class="citation"&gt;Schnuerch et al. (2020)&lt;/span&gt;.&lt;/p&gt;'><sup>1</sup></a><sup>,</sup><a class="footnote-ref" tabindex="0" data-bs-toggle="popover" data-bs-content='&lt;p&gt;Note that this estimate of Cohen’s d as well as the CI
are based on the assumption of a fixed sample size and, thus, might be
biased toward an overestimation of the true effect size. See for details
&lt;span class="citation"&gt;Schnuerch et al. (2020)&lt;/span&gt;.&lt;/p&gt;'><sup>2</sup></a></p>
</div>
</div>
<div class="section level2 unnumbered">
<h2 class="unnumbered" id="references">References<a class="anchor" aria-label="anchor" href="#references"></a>
</h2>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0" line-spacing="2">
<div id="ref-schnuerch2020a" class="csl-entry">
Schnuerch, M., Erdfelder, E., &amp; Heck, D. W. (2020). Sequential
hypothesis tests for multinomial processing tree models. <em>Journal of
Mathematical Psychology</em>, <em>95</em>, 102326. <a href="https://doi.org/10.1016/j.jmp.2020.102326" class="external-link">https://doi.org/10.1016/j.jmp.2020.102326</a>
</div>
</div>
</div>

  </main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside>
</div>



    <footer><div class="pkgdown-footer-left">
  <p>Developed by Meike Steinhilber, Martin Schnuerch, Anna-Lena Schubert.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.1.3.</p>
</div>

    </footer>
</div>





  </body>
</html>
