# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function(a, b) {
    .Call('_sprt_test', PACKAGE = 'sprt', a, b)
}

dnf_cpp <- function(x, df1, df2, ncp, log = FALSE) {
    .Call('_sprt_dnf_cpp', PACKAGE = 'sprt', x, df1, df2, ncp, log)
}

dnt_cpp <- function(x, df, ncp, log = FALSE) {
    .Call('_sprt_dnt_cpp', PACKAGE = 'sprt', x, df, ncp, log)
}

